### ISSUE TITLE
Attempt: proper use of SVP solutions

### ISSUE THREAD

**Issue by ccorn** [lducas/SchnorrGate#1]
I have some commits on [my branch](https://github.com/ccorn/SchnorrGate/commits/ccorn) that you might want to cherry-pick (except for the disabling of the external enumerator which I need to get `fplll` running at all). The essential one addresses [this observation](https://crypto.stackexchange.com/a/88647/23164) and focuses on those solutions that can produce small `|u - vN|`. As it turns out, lots of SVP solutions actually yield `u/v` close to 1 or `1/N` instead of `N`. In the `1/N` case, we can repair that with a sign flip, thus swapping `u` and `v`.

Anyway, I suspect that the Mar 3 paper does not specify the matrix correctly, as the matrix could as well be processed without the common factor `N`.

**Comment by lducas** [comment]
Thanks you very much for your comment and PR. I will decline it, but it's on me to explicit the purpose of this repository. 

The purpose of this repository is to document the precise algorithm of [Sch21, march 3rd] as is, as well as to comment on its long history. 

The goal was to quickly alleviate concerns regarding a sudden "destruction" of RSA from this approach, and avoid a crypto-panic with potentially bad consequences for real-world security: an unwarranted panic-transition away from RSA sounds like a terrible outcome. Transitions takes time and care. 

The SageMath script is only a small portion of that effort; the most important point is prior history of this approach.

As such, the purpose of this repo is *not* to include potential improvements, for which there are certainly many directions. None of which I seriously expect to live up to Schnorr's claim, unfortunately. I certainly encourage further implementation, research,  and documentation efforts nevertheless, but I do warrant caution, review, and due process before public release of fantastic cryptanalytic claims.

Any PR / comments serving this purpose would be gladly accepted, may it be about fixing potential mistakes in the code compared to [Sch21], historical references on this approach, or pointers to new research on the matter.

**Comment by ccorn** [comment]
I have actually expected this and therefore have not filed this issue as a merge request. It is mainly intended to point to a (rather obvious) variant for experimentation.
