### ISSUE TITLE
Something that seems strange to me - similar success rates without SVP

### ISSUE THREAD

**Issue by hansjoachimknobloch** [lducas/SchnorrGate#2]
Please excuse my bothering you. I am still struggling to grasp the specifics of Schnorr's factoring algorithm, so I've been experimenting a bit with your code.

In README.md you write:
"Closer inspection of typical shortest showed that the vector `e` is typically very sparse, say a single `1` and a single `-1`.

Upon more closer inspection, these single `1` and `-1` are typically in the elements `e[i]` where `f[i]` equals 1 or 2 (or in in rare cases `f[i]==3`, maybe more often for larger bits sizes) and the `-1` (if present) typically has the smaller index `i` than the `1`. (Rarely there are  `e[i]` equal to `-2`and /or `-3`, but still where `f[i]`is equal to 1 or 2.)

Since `f[]` is randomized, it might be more or less equivalent to pick two distinct primes from `P`  (or `1`)  at random and set `u` and `v` to the larger resp. smaller of these two values instead of spending the effort to compute the SVP.
That all seems strange to me.

Indeed, the following function yields similar success rates (only much faster of course):
```python
def test_random(N, n):
	P = first_primes(n)
	Q = [1] + P
	i = randrange(0,n+1)
	while True:
		j = randrange(0,n+1)
		if (i != j):
			break
	u = Q[max(i,j)]
	v = Q[min(i,j)]
	return is_smooth(u - v*N, P) 
```

**Comment by lducas** [comment]
Yes, precisely: in this particular version of Schnorr's attack, SVP is not going to yield anything helpful. This is due to the incorrect volume computation linked in the readme.
