### ISSUE TITLE
Rounding issues

### ISSUE THREAD

**Issue by GregoryMorse** [lducas/SchnorrGate#4]
I would expect only integer operations e.g. // not /.  And I would expect floor and ceil not round.  Also taking natural log and scaling it looks inaccurate if floating point number are involved even if the primes are small the scaling factor might not be.  a ln b==ln b^a might be necessary for accuracy but a big integer ln is needed.  Of course sage is used.  But these details are important to verify.

Are any of these rounding issues potential implementation problems which would cause this code to find no fac relations?

Why not verify the paper example?

I would like to see the code working in at least some trivial cases so we can know the implementation is correct.

**Comment by lducas** [comment]
The code appears to be working in some cases, as already reported in the readme:
"Running b=10, n=47, t=1000, we obtained 353 Factoring Relation found out of 1000 trials. "
